---
repos:
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [-c=.yamllint]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
            args: [--width, '200']
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.2
      hooks:
          - id: shellcheck
            files: |
                (?x)(
                    ^gtkwave3-gtk3/build-mac-app\.sh$
                )
