#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

SOURCE_DIR=$(dirname "$0")
CONFIGURE_SCRIPT="$SOURCE_DIR/configure"


ARCH=""
PASSTHROUGH_OPTIONS=()
while [ $# -ge 1 ]; do
    case "$1" in
        -p|--prefix)
            PREFIX=$(readlink -f "$2")
            PASSTHROUGH_OPTIONS+=("$1")
            PASSTHROUGH_OPTIONS+=("$PREFIX")
            shift
            shift
            ;;
        -arch|--arch)
            ARCH="$2"
            shift
            shift
            ;;
        *)
            # Passthrough option
            PASSTHROUGH_OPTIONS+=("$1")
            shift
            ;;
    esac
done

case "$ARCH" in
    x86_64|arm64)
        export CPPFLAGS="${CFLAGS:+} -arch $ARCH"
        export CFLAGS="${CFLAGS:+} -arch $ARCH"
        export CXXFLAGS="${CXXFLAGS:+} -arch $ARCH"
        export LDFLAGS="${LDFLAGS:+} -arch $ARCH"
        ;;
    "")
        # no --arch given
        ;;
    *)
        echo "Unhandled architecture '$ARCH'"
        exit 1
        ;;
esac

# Run the configure script with the passthrough options
"$CONFIGURE_SCRIPT" "${PASSTHROUGH_OPTIONS[@]}"
