---
# yaml-language-servzer: $schema=https://json.schemastore.org/github-workflow.json
name: Build GTKWave

on:
    push:
    schedule:
        - cron: 0 0 * * *  # nightly
    workflow_dispatch:
        inputs:
            debug_at_start:
                type: boolean
                description: Spawn a shell at the beginning of a run
                required: false
                default: false
            debug_on_fail:
                type: boolean
                description: Spawn a shell if there is a failure
                required: false
                default: false
            debug_at_end:
                type: boolean
                description: Spawn a shell at the end of a run
                required: false
                default: false


jobs:

    msys2:
        if: false  # disable for mac testing
        runs-on: windows-latest
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                target:
                    - {msys2: MINGW32, arch: i686}
                    - {msys2: MINGW64, arch: x86_64}
                gtk: [2, 3]
        continue-on-error: true
        defaults:
            run:
                shell: msys2 {0}
        env:
            MINGW_INSTALLS: ${{ matrix.target.msys2 }}
        steps:

            - run: git config --global core.autocrlf input
              shell: bash

            - uses: actions/checkout@v2

            - uses: msys2/setup-msys2@v2
              with:
                  update: true
                  install: >
                      base-devel
                      git
                      mingw-w64-${{ matrix.target.arch }}-toolchain
                      mingw-w64-${{ matrix.target.arch }}-autotools
                  msystem: ${{ matrix.target.msys2 }}

            - name: Build package
              working-directory: MSYS2/gtk${{ matrix.gtk }}
              run: |
                  tries=0
                  # Try building three times due to the arbitrary 'Bad address' error
                  while [ $tries -lt 3 ]; do
                    makepkg-mingw --noconfirm --noprogressbar -sCLfc && exit 0
                    tries=$((tries+1))
                  done
                  exit 1

            - name: Install and create standalone package
              working-directory: ./MSYS2/gtk${{ matrix.gtk }}
              run: |
                  pacman -U --noconfirm mingw-*gtkwave*.pkg.tar.zst
                  mv mingw-*gtkwave*.pkg.tar.zst ../../
                  ../standalone_pkg.sh

            - uses: actions/upload-artifact@v2
              with:
                  path: |
                      mingw-*gtkwave*.pkg.tar.zst
                      gtkwave_*_standalone.tgz

    nightly:
        if: false  # disable for mac testing
        # if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        needs: [msys2]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@v2
            - uses: eine/tip@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: nightly
                  rm: true
                  files: artifact/*

    mac-app:
        runs-on: macos-latest
        defaults:
            run:
                working-directory: build
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3
            - name: Make build dir
              run: |
                  /bin/pwd
                  mkdir -p gtkwave/build
                  cd gtkwave/build
                  /bin/pwd
              working-directory: ..
            # Enable tmate debugging of manually-triggered workflows if the input option was provided
            - name: Spawn shell at beginning
              uses: mxschmitt/action-tmate@v3
              if: ${{ inputs.debug_at_start && github.event_name == 'workflow_dispatch' }}
              with:
                  limit-access-to-actor: true
            - name: Prep cache directories
              run: |
                  sudo sh -c "echo nix >> /etc/synthetic.conf"
                  sudo sh -c "echo LABEL=Nix\040Store /nix apfs rw,nobrowse,suid,owners >> /etc/fstab"
                  sudo /usr/sbin/diskutil apfs addVolume disk1 APFS "Nix Store" -mountpoint /nix
                  sudo /usr/sbin/dseditgroup -o create -i 30000 nixbld
                  sudo /bin/mkdir -p /nix/store /nix/var/cache/ccache
                  sudo /usr/sbin/chown -R root:nixbld /nix
            - name: Cache
              uses: actions/cache@v3.2.2
              with:
                  key: ${{ runner.os }}-gtkwave-mac-app
                  path: >
                      /nix/store
                      /nix/var/cache/ccache
            - name: Install Nix
              uses: cachix/install-nix-action@v18
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
                  extra_nix_config: |
                      extra-platforms = x86_64-darwin aarch64-darwin
                      experimental-features = nix-command flakes

            # Debug failures with shell (defaults off)
            - name: Spawn shell at end or failure
              uses: mxschmitt/action-tmate@v3
              if: ${{ ((failure() && inputs.debug_on_fail) || inputs.debug_at_end) && github.event_name == 'workflow_dispatch' }}
              with:
                  limit-access-to-actor: true
